export const data = [
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/meghalaya-kaziranga-exclusive/boating-in-meghalaya.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "0",
		day: "6N-7D",
		location: "Guwahati",
		pkgName: "Meghalaya With Kaziranga - Exclusive Escape",
		price: "27,999",
		bookDate: "25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/kashmir-winter-backpacking/wanderon-kashmir-1.jpg",
		imgTitle1: "Trekking",
		imgTitle2: "Snow Paradise",
		value: "0",
		day: "5N-6D",
		location: "Srinagar",
		pkgName: "Kashmir Winter Expedition",
		price: "26,499",
		bookDate: "18, 25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/meghalaya-with-kaziranga-road-trip-6n-7d/kaziranga-open-jeep-safari.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "0",
		day: "6N-7D",
		location: "Guwahati",
		pkgName: "Meghalaya With Kaziranga - Road Trip",
		price: "24,999",
		bookDate: "18, 25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/meghalaya-kaziranga-exclusive/boating-in-meghalaya.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "0",
		day: "6N-7D",
		location: "Guwahati",
		pkgName: "Meghalaya With Kaziranga - Exclusive Escape",
		price: "27,999",
		bookDate: "25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/kashmir-winter-backpacking/wanderon-kashmir-1.jpg",
		imgTitle1: "Trekking",
		imgTitle2: "Snow Paradise",
		value: "0",
		day: "5N-6D",
		location: "Srinagar",
		pkgName: "Kashmir Winter Expedition",
		price: "26,499",
		bookDate: "18, 25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/meghalaya-with-kaziranga-road-trip-6n-7d/kaziranga-open-jeep-safari.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "0",
		day: "6N-7D",
		location: "Guwahati",
		pkgName: "Meghalaya With Kaziranga - Road Trip",
		price: "24,999",
		bookDate: "18, 25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/spiti-winter/wanderon-spiti-winter-8.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "0",
		day: "6N-7D",
		location: "Delhi",
		pkgName: "Spiti Winter - Exclusive Escape",
		price: "23,999",
		bookDate: "18, 25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/spiti-winter-budget/wanderon-spiti-winter-13.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "0",
		day: "6N-7D",
		location: "Delhi",
		pkgName: "Spiti Winter - Bliss in Budget",
		price: "27,999",
		bookDate: "18, 25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/meghalaya-road-trip/wanderon-meghalaya-1.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "0",
		day: "6N-7D",
		location: "Delhi",
		pkgName: "Meghalaya Road Trip",
		price: "27,999",
		bookDate: "18, 25 Mar",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/meghalaya-kaziranga-exclusive/boating-in-meghalaya.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "1",
		day: "6N-7D",
		location: "Guwahati",
		pkgName: "Meghalaya With Kaziranga - Exclusive Escape",
		price: "27,999",
		bookDate: "06, 15, 29 apr",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/manali-lahaul-good-friday/wanderon-manali-2.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "1",
		day: "2N-3D",
		location: "Delhi",
		pkgName: "Manali Lahaul Atal Tunnel",
		price: "7,999",
		bookDate: "06 apr",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/kashmir-spring-bliss-in-budget/wanderon-kashmir-10.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "1",
		day: "6N-7D",
		location: "Kasmir",
		pkgName: "Kashmir Spring - Bliss In Budget",
		price: "20,499",
		bookDate: "01, 07, 15, 22, 29 apr",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/meghalaya-kaziranga-exclusive/boating-in-meghalaya.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "1",
		day: "6N-7D",
		location: "Guwahati",
		pkgName: "Meghalaya With Kaziranga - Exclusive Escape",
		price: "27,999",
		bookDate: "06, 15, 29 apr",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/manali-lahaul-good-friday/wanderon-manali-2.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "1",
		day: "2N-3D",
		location: "Delhi",
		pkgName: "Manali Lahaul Atal Tunnel",
		price: "7,999",
		bookDate: "06 apr",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/kashmir-spring-bliss-in-budget/wanderon-kashmir-10.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "1",
		day: "6N-7D",
		location: "Kasmir",
		pkgName: "Kashmir Spring - Bliss In Budget",
		price: "20,499",
		bookDate: "01, 07, 15, 22, 29 apr",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/manali-leh-manali/wanderon-ladakh-8.jpg",
		imgTitle1: "Camping",
		imgTitle2: "Trekking",
		value: "2",
		day: "8N-9D",
		location: "Delhi",
		pkgName: "Manali Leh Manali",
		price: "20,499",
		bookDate: "27 May",
	},
	{
		url: "https://ik.imagekit.io/workcations/gallery/triplist/mcleodganj-bir-tirthan/wanderon-tirthan-1.jpg",
		imgTitle1: "Rafting",
		imgTitle2: "Trekking",
		value: "2",
		day: "4N-5D",
		location: "Delhi",
		pkgName: "Mcleodganj Bir Tirthan",
		price: "20,499",
		bookDate: "27 May",
	},
];
